import sys
import re

file_path = 'c:/Users/ADMIIN/VScode/final-project/web-app/src/pages/practice/SchoolExamPage.tsx'
with open(file_path, 'r', encoding='utf-8') as f: content = f.read()

# Replace conflict blocks
# We want to match <<<<<<< HEAD\n...\n=======\n(...)\n>>>>>>> b0f699e...
# and replace it with \1 (the content between ======= and >>>>>>>)
pattern = re.compile(r'<<<<<<< HEAD\n.*?=======\n(.*?)\n>>>>>>> [a-f0-9]+', re.DOTALL)
content = pattern.sub(r'\1', content)

# additional generic replacements for mojibake
content = content.replace('Ä‘', 'đ')
content = content.replace('áº¡', 'ạ')
content = content.replace('Ã¡', 'á')
content = content.replace('Ã ', 'à')
content = content.replace('Ã¢', 'â')
content = content.replace('áº¥', 'ấ')
content = content.replace('áº§', 'ầ')
content = content.replace('áº­', 'ậ')
content = content.replace('áº£', 'ả')
content = content.replace('Ã£', 'ã')
content = content.replace('áº«', 'ẫ')
content = content.replace('áº¯', 'ắ')
content = content.replace('áº±', 'ằ')
content = content.replace('áº·', 'ặ')
content = content.replace('Ã©', 'é')
content = content.replace('Ã¨', 'è')
content = content.replace('áº¹', 'ẹ')
content = content.replace('áº»', 'ẻ')
content = content.replace('áº½', 'ẽ')
content = content.replace('Ãª', 'ê')
content = content.replace('áº¿', 'ế')
content = content.replace('á» ', 'ề')
content = content.replace('á»‡', 'ệ')
content = content.replace('á»ƒ', 'ể')
content = content.replace('á»…', 'ễ')
content = content.replace('Ã\xad', 'í')
content = content.replace('Ã¬', 'ì')
content = content.replace('á»‹', 'ị')
content = content.replace('á»‰', 'ỉ')
content = content.replace('Ä©', 'ĩ')
content = content.replace('Ã³', 'ó')
content = content.replace('Ã²', 'ò')
content = content.replace('á»\x8d', 'ọ')
content = content.replace('á» ', 'ỏ')
content = content.replace('Ãµ', 'õ')
content = content.replace('Ã´', 'ô')
content = content.replace('á»‘', 'ố')
content = content.replace('á»“', 'ồ')
content = content.replace('á»™', 'ộ')
content = content.replace('á»•', 'ổ')
content = content.replace('á»—', 'ỗ')
content = content.replace('Æ¡', 'ơ')
content = content.replace('á»›', 'ớ')
content = content.replace('á»\x9d', 'ờ')
content = content.replace('á»£', 'ợ')
content = content.replace('á»Ÿ', 'ở')
content = content.replace('á»¡', 'ỡ')
content = content.replace('Ãº', 'ú')
content = content.replace('Ã¹', 'ù')
content = content.replace('á»¥', 'ụ')
content = content.replace('á»§', 'ủ')
content = content.replace('Å©', 'ũ')
content = content.replace('Æ°', 'ư')
content = content.replace('á»©', 'ứ')
content = content.replace('á»«', 'ừ')
content = content.replace('á»±', 'ự')
content = content.replace('á»\xad', 'ử')
content = content.replace('á»¯', 'ữ')
content = content.replace('Ã½', 'ý')
content = content.replace('á»³', 'ỳ')
content = content.replace('á»µ', 'ỵ')
content = content.replace('á»·', 'ỷ')
content = content.replace('á»¹', 'ỹ')
content = content.replace('Ä ', 'Đ')

content = content.replace('Ã', 'í') # catch remaining?
# Let's fix uppercase variants
content = content.replace('Ã\x81', 'Á')
content = content.replace('Ã\x80', 'À')
content = content.replace('Ã\x82', 'Â')

with open(file_path, 'w', encoding='utf-8') as f: f.write(content)
print('Done fixing mojibake')
